-- Connect hackathon: Unity Catalog schema.
-- Everything is mock data. Comments are deliberate: Genie and reviewers read them.
-- Re-runnable: CREATE OR REPLACE on every object.

CREATE SCHEMA IF NOT EXISTS workspace.jobsearch
  COMMENT 'Connect: student job search built on real human connections, not AI-agent mass applications. Mock data for the Deloitte x Databricks hackathon.';

-- Volume that holds the seed files uploaded by scripts/load.py.
CREATE VOLUME IF NOT EXISTS workspace.jobsearch.seed
  COMMENT 'Seed JSONL files generated by data/generate_mock.py. Loaded into tables with COPY INTO.';

CREATE OR REPLACE TABLE workspace.jobsearch.companies (
  id            STRING NOT NULL COMMENT 'Company id, e.g. c001',
  name          STRING NOT NULL COMMENT 'Fictional company name',
  vertical      STRING NOT NULL COMMENT 'swe | consulting | finance',
  size          STRING          COMMENT 'small | mid | large',
  hq            STRING          COMMENT 'Headquarters city',
  careers_url   STRING          COMMENT 'Fake careers page URL (example.com)',
  CONSTRAINT companies_pk PRIMARY KEY (id)
)
USING DELTA
COMMENT 'Employers with open positions. Fictional names.';

CREATE OR REPLACE TABLE workspace.jobsearch.people (
  id                 STRING NOT NULL COMMENT 'Person id, e.g. p0001',
  name               STRING NOT NULL COMMENT 'Synthetic full name',
  headline           STRING          COMMENT 'LinkedIn-style headline: title at company | school year',
  company            STRING          COMMENT 'Employer name (denormalized for readability)',
  company_id         STRING          COMMENT 'FK to companies.id',
  title              STRING          COMMENT 'Current job title',
  school             STRING          COMMENT 'Undergraduate school',
  major              STRING          COMMENT 'Undergraduate major',
  grad_year          INT             COMMENT 'Undergraduate graduation year',
  function           STRING          COMMENT 'Job function: engineering | consulting | cybersecurity | recruiting | ...',
  industry           STRING          COMMENT 'software | professional services | financial services | ...',
  seniority          STRING          COMMENT 'intern | analyst | associate | senior_associate | manager | senior_manager | director | vp | partner | executive',
  hometown           STRING          COMMENT 'Where they are FROM (City, ST). Distinct from location on purpose.',
  high_school        STRING          COMMENT 'High school. Sharper hook than hometown.',
  clubs              ARRAY<STRING>   COMMENT 'Student organizations, Greek letters, honour societies',
  communities        ARRAY<STRING>   COMMENT 'Non-school life: ROTC, Eagle Scouts, a church, a rec league',
  interests          ARRAY<STRING>   COMMENT 'Specific interests: "Formula 1", not "sports"',
  projects           ARRAY<STRING>   COMMENT 'Side projects worth asking about',
  education          ARRAY<STRUCT<school: STRING, degree: STRING, field: STRING, startYear: INT, endYear: INT, activities: ARRAY<STRING>>>
                                     COMMENT 'Education history with activities per school',
  roles              ARRAY<STRUCT<company: STRING, title: STRING, function: STRING, industry: STRING, seniority: STRING, startYear: INT, endYear: INT, clients: ARRAY<STRING>, programs: ARRAY<STRING>>>
                                     COMMENT 'Work history, oldest first; endYear NULL = current. clients and programs are named tier-4 hooks.',
  posts              ARRAY<STRUCT<id: STRING, kind: STRING, title: STRING, excerpt: STRING, topics: ARRAY<STRING>, url: STRING, publishedAt: STRING>>
                                     COMMENT 'Recent posts, talks, papers. publishedAt is ISO 8601; relevance decays over ~30 days.',
  events             ARRAY<STRUCT<name: STRING, kind: STRING, date: STRING, org: STRING>>
                                     COMMENT 'Recent events attended. date is ISO 8601; relevance decays over ~72 hours.',
  vertical           STRING          COMMENT 'swe | consulting | finance',
  location           STRING          COMMENT 'Current work location',
  openness_to_chat   DOUBLE          COMMENT '0-1 likelihood they take a coffee chat with a student',
  linkedin_url       STRING          COMMENT 'Fake profile URL (example.com)',
  CONSTRAINT people_pk PRIMARY KEY (id),
  CONSTRAINT people_company_fk FOREIGN KEY (company_id) REFERENCES workspace.jobsearch.companies (id)
)
USING DELTA
COMMENT 'Mock professional network (stand-in for LinkedIn data). Every row is synthetic. Carries the small nameable things a coffee chat runs on: high school, communities, specific interests, programmes, recent posts and events.';

CREATE OR REPLACE TABLE workspace.jobsearch.positions (
  id                 STRING NOT NULL COMMENT 'Position id, e.g. j001',
  company_id         STRING NOT NULL COMMENT 'FK to companies.id',
  title              STRING NOT NULL COMMENT 'Role title',
  type               STRING NOT NULL COMMENT 'internship | full_time | research',
  vertical           STRING NOT NULL COMMENT 'swe | consulting | finance',
  location           STRING          COMMENT 'Role location or Remote',
  opens_on           DATE            COMMENT 'Date applications open',
  closes_on          DATE            COMMENT 'Date applications close',
  target_grad_years  ARRAY<INT>      COMMENT 'Graduation years the role is intended for',
  description        STRING          COMMENT 'Short role description',
  posted_url         STRING          COMMENT 'Fake posting URL (example.com)',
  CONSTRAINT positions_pk PRIMARY KEY (id),
  CONSTRAINT positions_company_fk FOREIGN KEY (company_id) REFERENCES workspace.jobsearch.companies (id)
)
USING DELTA
COMMENT 'Jobs, internships, and research roles with application windows.'
-- change data feed is required for the Vector Search delta-sync index
TBLPROPERTIES ('delta.enableChangeDataFeed' = 'true');

CREATE OR REPLACE TABLE workspace.jobsearch.position_requirements (
  position_id   STRING NOT NULL COMMENT 'FK to positions.id',
  requirement   STRING NOT NULL COMMENT 'Named requirement, e.g. Security+, Python, Excel modeling',
  kind          STRING NOT NULL COMMENT 'skill | certification | degree | experience',
  required      BOOLEAN         COMMENT 'true = hard requirement, false = preferred',
  CONSTRAINT position_requirements_fk FOREIGN KEY (position_id) REFERENCES workspace.jobsearch.positions (id)
)
USING DELTA
COMMENT 'Public prerequisites per position. Drives the skill-gap recommender.';

CREATE OR REPLACE TABLE workspace.jobsearch.students (
  id                     STRING NOT NULL COMMENT 'Student id, e.g. s001',
  name                   STRING NOT NULL COMMENT 'Synthetic full name',
  email                  STRING          COMMENT 'Fake email (example.edu)',
  school                 STRING          COMMENT 'Current school',
  major                  STRING          COMMENT 'Declared major',
  grad_year              INT             COMMENT 'Expected graduation year',
  target_verticals       ARRAY<STRING>   COMMENT 'Verticals they want: swe | consulting | finance',
  target_companies       ARRAY<STRING>   COMMENT 'Companies they named in the questionnaire',
  skills                 ARRAY<STRING>   COMMENT 'Self-reported skills from resume + questionnaire',
  certifications         ARRAY<STRING>   COMMENT 'Certifications they hold',
  interests              ARRAY<STRING>   COMMENT 'Specific interests from the questionnaire',
  projects               ARRAY<STRING>   COMMENT 'Side projects they mentioned',
  hometown               STRING          COMMENT 'Where they are FROM (City, ST)',
  high_school            STRING          COMMENT 'High school',
  clubs                  ARRAY<STRING>   COMMENT 'Student organizations they are in',
  communities            ARRAY<STRING>   COMMENT 'Non-school communities: ROTC, scouts, church, rec league',
  events                 ARRAY<STRUCT<name: STRING, kind: STRING, date: STRING, org: STRING>>
                                         COMMENT 'Recent events attended (career fairs, case competitions)',
  resume_text            STRING          COMMENT 'Plain-text resume as uploaded',
  questionnaire_answers  STRING          COMMENT 'JSON string of the onboarding questionnaire answers',
  created_at             TIMESTAMP       COMMENT 'Account creation time',
  CONSTRAINT students_pk PRIMARY KEY (id)
)
USING DELTA
COMMENT 'Platform users. Account creation is required before any matching.'
-- change data feed is required for the Vector Search delta-sync index
TBLPROPERTIES ('delta.enableChangeDataFeed' = 'true');

CREATE OR REPLACE TABLE workspace.jobsearch.connection_paths (
  student_id   STRING NOT NULL COMMENT 'FK to students.id',
  person_id    STRING NOT NULL COMMENT 'FK to people.id',
  path_type    STRING NOT NULL COMMENT 'same_high_school | same_club | same_community | alumni_at_target_company | same_event | shared_interest | same_school | same_hometown | same_major',
  strength     DOUBLE NOT NULL COMMENT 'Base weight of this hook type, 0-1',
  detail       STRING          COMMENT 'The specific shared thing: club name, company, hometown, major',
  CONSTRAINT connection_paths_student_fk FOREIGN KEY (student_id) REFERENCES workspace.jobsearch.students (id),
  CONSTRAINT connection_paths_person_fk  FOREIGN KEY (person_id)  REFERENCES workspace.jobsearch.people (id)
)
USING DELTA
COMMENT 'Precomputed human hooks between each student and each person. One row per shared attribute. The product core.';
