/**
 * Derives the two build inputs the app needs from design/terminal-brutalist,
 * so that folder stays the single source of truth and nothing is hand-copied.
 *
 * 1. `bundle.js` -> public/tb/bundle.js. It is a classic script defining one
 *    global (TB), so Next can only serve it from public/.
 *
 * 2. `bundle.css` -> src/styles/tb-bundle.generated.css, with the Google Fonts
 *    `@import` removed. CSS requires @import before any other rule; once a
 *    bundler inlines this stylesheet after Tailwind's, that nested import is
 *    no longer at the top of the file and the build fails outright. The fonts
 *    are not lost — layout.tsx loads Space Grotesk and Space Mono through
 *    next/font, which is the self-hosting route the system recommends anyway.
 *
 * Both outputs are gitignored and regenerated on every dev and build, so the
 * served copies cannot drift from the design system.
 */
import { copyFile, mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const design = resolve(root, "design/terminal-brutalist");

const script = resolve(root, "public/tb/bundle.js");
await mkdir(dirname(script), { recursive: true });
await copyFile(resolve(design, "components/bundle.js"), script);

const source = await readFile(resolve(design, "components/bundle.css"), "utf8");
const stripped = source.replace(/^@import url\([^)]*\);\s*/m, "");
if (stripped === source) {
  console.warn("[design] no @import found in bundle.css — the upstream file may have changed");
}

const out = resolve(root, "src/styles/tb-bundle.generated.css");
await mkdir(dirname(out), { recursive: true });
await writeFile(
  out,
  "/* GENERATED by scripts/sync-design.mjs from design/terminal-brutalist.\n" +
    "   Do not edit: every change is overwritten on the next dev or build.\n" +
    "   The Google Fonts @import is stripped here; next/font loads the families. */\n\n" +
    stripped,
);

console.log("[design] synced bundle.js and bundle.css");
