# Databricks notebook source
# MAGIC %md
# MAGIC # Common Ground — data layer walkthrough
# MAGIC
# MAGIC A job-search platform for students built on **real human connections**, not AI-agent mass applications.
# MAGIC Everything in `workspace.jobsearch` is mock data generated by `data/generate_mock.py` (seed `20260919`).
# MAGIC
# MAGIC This notebook walks the schema and the four core views, then the two AI-assisted objects.
# MAGIC Import it into the workspace (Workspace → Import → File) or run the cells from a SQL editor.

# COMMAND ----------

# MAGIC %sql
# MAGIC USE CATALOG workspace;
# MAGIC USE SCHEMA jobsearch;
# MAGIC SHOW TABLES;

# COMMAND ----------

# MAGIC %md
# MAGIC ## 1. The raw tables
# MAGIC `students` ← questionnaire + resume · `people` ← mock professional network · `positions` + `position_requirements` ← public postings ·
# MAGIC `connection_paths` ← precomputed human hooks (the product core).

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT 'students' AS tbl, count(*) AS rows FROM students
# MAGIC UNION ALL SELECT 'people', count(*) FROM people
# MAGIC UNION ALL SELECT 'companies', count(*) FROM companies
# MAGIC UNION ALL SELECT 'positions', count(*) FROM positions
# MAGIC UNION ALL SELECT 'position_requirements', count(*) FROM position_requirements
# MAGIC UNION ALL SELECT 'connection_paths', count(*) FROM connection_paths;

# COMMAND ----------

# MAGIC %sql
# MAGIC -- A student, as the questionnaire captured them
# MAGIC SELECT id, name, school, major, grad_year, target_verticals, skills, certifications, clubs, hometown,
# MAGIC        from_json(questionnaire_answers, 'map<string,string>') AS questionnaire
# MAGIC FROM students WHERE id = 's001';

# COMMAND ----------

# MAGIC %sql
# MAGIC -- Hook types and how much of the graph each one contributes
# MAGIC SELECT path_type, count(*) AS edges, round(avg(strength), 2) AS base_strength
# MAGIC FROM connection_paths GROUP BY path_type ORDER BY base_strength DESC;

# COMMAND ----------

# MAGIC %md
# MAGIC ## 2. `v_student_people_matches` — who to actually talk to
# MAGIC Combines every hook between a student and a person (noisy-OR), weights by the person's openness to a coffee chat,
# MAGIC and boosts people at companies hiring in the student's vertical. `hook` is display-ready.

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT person_name, company, title, best_path_type, at_target_company, openness_to_chat, match_score, hook
# MAGIC FROM v_student_people_matches
# MAGIC WHERE student_id = 's001'
# MAGIC ORDER BY match_score DESC LIMIT 5;

# COMMAND ----------

# MAGIC %md
# MAGIC ## 3. `v_student_position_matches` — what to aim for
# MAGIC Vertical fit (40/25) + grad-year eligibility (20) + skill overlap (≤25) + cert coverage (≤10) + timing (±) − missing required cert (10).
# MAGIC `reasons[]` is the explanation the UI shows.

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT title, company, type, window_status, days_until_open, match_score, reasons
# MAGIC FROM v_student_position_matches
# MAGIC WHERE student_id = 's005'
# MAGIC ORDER BY match_score DESC LIMIT 5;

# COMMAND ----------

# MAGIC %md
# MAGIC ## 4. `v_skill_gaps` — what's between the student and the role
# MAGIC Only for positions the student already scores ≥ 50 on. `required = true` rows are hard blockers.

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT title, company, match_score, requirement, kind, required, window_status
# MAGIC FROM v_skill_gaps
# MAGIC WHERE student_id = 's007' AND required
# MAGIC ORDER BY match_score DESC LIMIT 8;

# COMMAND ----------

# MAGIC %sql
# MAGIC -- Across all students: which required certifications block the most people?
# MAGIC SELECT requirement, count(DISTINCT student_id) AS students_blocked, count(DISTINCT position_id) AS positions
# MAGIC FROM v_skill_gaps WHERE kind = 'certification' AND required
# MAGIC GROUP BY requirement ORDER BY students_blocked DESC;

# COMMAND ----------

# MAGIC %md
# MAGIC ## 5. `v_opening_timeline` — start early
# MAGIC The product's positioning: adopt it at the start of college, because windows open months before students expect.

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT title, company, type, opens_on, closes_on, window_status, days_until_open, match_score
# MAGIC FROM v_opening_timeline
# MAGIC WHERE student_id = 's001' LIMIT 10;

# COMMAND ----------

# MAGIC %sql
# MAGIC -- Month-by-month: how many matched windows open, per vertical
# MAGIC SELECT date_trunc('month', opens_on) AS month, vertical, count(DISTINCT position_id) AS positions_opening
# MAGIC FROM v_opening_timeline GROUP BY 1, 2 ORDER BY 1, 2;

# COMMAND ----------

# MAGIC %md
# MAGIC ## 6. AI — only where it should be
# MAGIC Two places, both via Databricks `ai_query()` on a hosted foundation model. Neither touches outreach or applications.
# MAGIC One model call per row, so always filter by student.

# COMMAND ----------

# MAGIC %sql
# MAGIC -- Skill-gap advice: how to actually close the gap
# MAGIC SELECT title, company, requirement, advice
# MAGIC FROM v_skill_gap_advice
# MAGIC WHERE student_id = 's007' AND requirement = 'Security+' LIMIT 1;

# COMMAND ----------

# MAGIC %sql
# MAGIC -- Resume tailoring, on demand, for one student × one position
# MAGIC SELECT title, company, tailored_resume FROM tailor_resume('s005', 'j026');

# COMMAND ----------

# MAGIC %md
# MAGIC ## 7. Semantic search over positions (Vector Search)
# MAGIC Delta-sync index `positions_index` on `positions.description`, embedded with `databricks-gte-large-en`.
# MAGIC Lets the questionnaire's free-text answer ("I want to build things people use") find roles without keyword overlap.

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT id, title, search_score
# MAGIC FROM vector_search(index => 'workspace.jobsearch.positions_index',
# MAGIC                    query_text => 'hands-on backend engineering with mentorship at a small team',
# MAGIC                    num_results => 5);

# COMMAND ----------

# MAGIC %md
# MAGIC ## 8. Home-screen payload
# MAGIC One row per student with top-5 people and top-5 positions as arrays of structs — what the frontend renders first.

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT * FROM v_student_home WHERE student_id = 's001';
