-- Affinity facts: the questionnaire's output and the scorer's input.
--
-- These ride on student_profiles rather than a table of their own. The RLS in
-- 0001 is generated by a loop over a fixed table list, and every policy there
-- keys on `auth.uid() = user_id`. A new COLUMN inherits all four policies, the
-- updated_at trigger and the table grant with no new policy surface. A new
-- TABLE would need four more policies, a grant and a join, and a typo in any
-- one of them is a cross-tenant leak.
--
-- One jsonb column rather than one column per facet, because computeGaps
-- iterates the whole object generically against the field registry — twenty
-- columns would turn that into twenty special cases, and every new question
-- would need a migration. Shape safety comes from AffinityFactsSchema.parse()
-- at both ends, the same zod-at-the-boundary discipline coursework, experience
-- and projects already use.
--
-- Meta is kept separate so affinity_facts stays byte-for-byte the shape
-- scoreAffinity consumes; wrapping every value in {value, confidence, source}
-- would force every predicate through an accessor.
alter table student_profiles
  add column affinity_facts      jsonb       not null default '{}'::jsonb,
  add column affinity_facts_meta jsonb       not null default '{}'::jsonb,
  add column intake_completed_at timestamptz;

comment on column student_profiles.affinity_facts is
  'AffinityFactsSchema. What the connection engine scores against.';
comment on column student_profiles.affinity_facts_meta is
  'FactsMetaSchema, keyed by intake field id. An entry here is what makes an '
  'empty value an ANSWER ("I am not in any club") rather than an unanswered gap.';
