/**
 * Canonical alias data.
 *
 * Keys are `normalizeText` output; values are canonical slugs. This is the
 * ONLY place an acronym is allowed to resolve. Generating acronyms
 * algorithmically ("virginia polytechnic institute and state university" ->
 * "vpisu", match against "VT"?) is a coin flip and two-letter acronyms collide
 * constantly, so an acronym either lives in this table or it does not resolve.
 *
 * Alias coverage is the whole ballgame for tiers 2-5: a missing alias silently
 * demotes a real connection to tier 11 with no error anywhere. The near-miss
 * report in score.ts exists so gaps here surface during rehearsal instead of
 * on stage.
 */

export const SCHOOL_ALIASES: Readonly<Record<string, string>> = Object.freeze({
  "virginia tech": "virginia-tech",
  "va tech": "virginia-tech",
  vt: "virginia-tech",
  vpi: "virginia-tech",
  "vpi and su": "virginia-tech",
  "virginia polytechnic institute": "virginia-tech",
  "virginia polytechnic institute and state university": "virginia-tech",
  "university of virginia": "u-virginia",
  uva: "u-virginia",
  "virginia commonwealth university": "vcu",
  vcu: "vcu",
  "george mason university": "george-mason",
  gmu: "george-mason",
  "james madison university": "james-madison",
  jmu: "james-madison",
  "william and mary": "william-mary",
  "college of william and mary": "william-mary",
  "old dominion university": "old-dominion",
  "george washington university": "george-washington",
  gwu: "george-washington",
  "georgetown university": "georgetown",
  "university of maryland": "u-maryland",
  umd: "u-maryland",
  "university of maryland college park": "u-maryland",
  "howard university": "howard",
  "north carolina state university": "nc-state",
  "nc state": "nc-state",
  "ncsu": "nc-state",
  "university of north carolina": "unc",
  "university of north carolina at chapel hill": "unc",
  unc: "unc",
  "duke university": "duke",
  "georgia institute of technology": "georgia-tech",
  "georgia tech": "georgia-tech",
  gatech: "georgia-tech",
  "massachusetts institute of technology": "mit",
  mit: "mit",
  "carnegie mellon university": "carnegie-mellon",
  cmu: "carnegie-mellon",
  "pennsylvania state university": "penn-state",
  "penn state": "penn-state",
  "university of pennsylvania": "u-penn",
  upenn: "u-penn",
  "the wharton school": "u-penn",
  "cornell university": "cornell",
  "new york university": "nyu",
  nyu: "nyu",
  "university of michigan": "u-michigan",
  "university of illinois urbana champaign": "uiuc",
  uiuc: "uiuc",
  "university of texas at austin": "ut-austin",
  "ut austin": "ut-austin",
  "university of california berkeley": "uc-berkeley",
  "uc berkeley": "uc-berkeley",
  berkeley: "uc-berkeley",
  "university of california los angeles": "ucla",
  ucla: "ucla",
  "stanford university": "stanford",
  "university of southern california": "usc",
  usc: "usc",
  "purdue university": "purdue",
  "ohio state university": "ohio-state",
  "the ohio state university": "ohio-state",
  "university of florida": "u-florida",
  "florida state university": "florida-state",
  "rutgers university": "rutgers",
  "boston university": "boston-u",
  "northeastern university": "northeastern",
  "university of washington": "u-washington",
  "texas a and m university": "texas-am",
  "texas am": "texas-am",
});

export const COMPANY_ALIASES: Readonly<Record<string, string>> = Object.freeze({
  deloitte: "deloitte",
  "deloitte consulting": "deloitte",
  "deloitte and touche": "deloitte",
  "deloitte llp": "deloitte",
  "deloitte and touche llp": "deloitte",
  pwc: "pwc",
  "pricewaterhousecoopers": "pwc",
  "price waterhouse coopers": "pwc",
  "pwc campus": "pwc",
  "pwc experienced": "pwc",
  ey: "ey",
  "ernst and young": "ey",
  kpmg: "kpmg",
  accenture: "accenture",
  "accenture federal services": "accenture",
  "booz allen": "booz-allen",
  "booz allen hamilton": "booz-allen",
  guidehouse: "guidehouse",
  "huron consulting": "huron",
  huron: "huron",
  "huron consulting group": "huron",
  "mckinsey": "mckinsey",
  "mckinsey and company": "mckinsey",
  bcg: "bcg",
  "boston consulting group": "bcg",
  "the boston consulting group": "bcg",
  bain: "bain",
  "bain and company": "bain",
  databricks: "databricks",
  anthropic: "anthropic",
  "goldman sachs": "goldman-sachs",
  goldman: "goldman-sachs",
  "jpmorgan chase": "jpmorgan",
  jpmorgan: "jpmorgan",
  "jp morgan": "jpmorgan",
  "morgan stanley": "morgan-stanley",
  "capital one": "capital-one",
  "amazon web services": "aws",
  aws: "aws",
  amazon: "amazon",
  "scale ai": "scale-ai",
  "rti international": "rti",
  rti: "rti",
  "department of homeland security": "dhs",
  dhs: "dhs",
  "centers for medicare and medicaid services": "cms",
  cms: "cms",
});

export const ORG_ALIASES: Readonly<Record<string, string>> = Object.freeze({
  "beta alpha psi": "beta-alpha-psi",
  bap: "beta-alpha-psi",
  "alpha kappa psi": "alpha-kappa-psi",
  akpsi: "alpha-kappa-psi",
  "delta sigma pi": "delta-sigma-pi",
  dsp: "delta-sigma-pi",
  "phi beta lambda": "phi-beta-lambda",
  "national society of black engineers": "nsbe",
  nsbe: "nsbe",
  "society of hispanic professional engineers": "shpe",
  shpe: "shpe",
  "society of women engineers": "swe",
  swe: "swe",
  "association for computing machinery": "acm",
  acm: "acm",
  "institute of electrical and electronics engineers": "ieee",
  ieee: "ieee",
  "alpha lambda delta": "alpha-lambda-delta",
  "beta gamma sigma": "beta-gamma-sigma",
  "management leadership for tomorrow": "mlt",
  mlt: "mlt",
  "sponsors for educational opportunity": "seo",
  "seo career": "seo",
  seo: "seo",
  "reserve officers training corps": "rotc",
  rotc: "rotc",
  "air force rotc": "afrotc",
  afrotc: "afrotc",
  "army rotc": "army-rotc",
  "corps of cadets": "corps-of-cadets",
  "consulting club": "consulting-club",
  "student government association": "sga",
  sga: "sga",
  "out in tech": "out-in-tech",
  ostem: "ostem",
  "oh stem": "ostem",
  "women in business": "women-in-business",
  "investment management club": "investment-club",
  "student managed investment fund": "investment-fund",
  "information technology society": "its",
  "cyber security club": "cyber-club",
  "cybersecurity club": "cyber-club",
  "data science club": "data-science-club",
});

export const PLACE_ALIASES: Readonly<Record<string, string>> = Object.freeze({
  "richmond va": "richmond-va",
  "greater richmond area": "richmond-va",
  "washington dc": "washington-dc",
  "washington district of columbia": "washington-dc",
  dc: "washington-dc",
  "dmv": "washington-dc",
  "northern virginia": "northern-va",
  nova: "northern-va",
  "new york city": "new-york-ny",
  nyc: "new-york-ny",
  "greater new york city area": "new-york-ny",
  "san francisco bay area": "san-francisco-ca",
  "bay area": "san-francisco-ca",
  sf: "san-francisco-ca",
  "virginia beach va": "virginia-beach-va",
  "hampton roads": "virginia-beach-va",
  "the triangle": "raleigh-nc",
  rtp: "raleigh-nc",
  "research triangle park": "raleigh-nc",
});

/** Expanded on the way into a place key so "VA" and "Virginia" agree. */
export const US_STATES: Readonly<Record<string, string>> = Object.freeze({
  alabama: "al", alaska: "ak", arizona: "az", arkansas: "ar", california: "ca",
  colorado: "co", connecticut: "ct", delaware: "de", florida: "fl", georgia: "ga",
  hawaii: "hi", idaho: "id", illinois: "il", indiana: "in", iowa: "ia",
  kansas: "ks", kentucky: "ky", louisiana: "la", maine: "me", maryland: "md",
  massachusetts: "ma", michigan: "mi", minnesota: "mn", mississippi: "ms",
  missouri: "mo", montana: "mt", nebraska: "ne", nevada: "nv",
  "new hampshire": "nh", "new jersey": "nj", "new mexico": "nm", "new york": "ny",
  "north carolina": "nc", "north dakota": "nd", ohio: "oh", oklahoma: "ok",
  oregon: "or", pennsylvania: "pa", "rhode island": "ri", "south carolina": "sc",
  "south dakota": "sd", tennessee: "tn", texas: "tx", utah: "ut", vermont: "vt",
  virginia: "va", washington: "wa", "west virginia": "wv", wisconsin: "wi",
  wyoming: "wy", "district of columbia": "dc",
});

/**
 * Dropped when deriving a school key. `institute`, `technology` and `state`
 * are deliberately NOT here — they are load-bearing for MIT, Georgia Tech and
 * Penn State, and dropping them collapses schools that are genuinely distinct.
 */
export const SCHOOL_STOPWORDS = new Set([
  "university", "universidad", "college", "the", "of", "at", "school", "system",
]);

export const COMPANY_SUFFIXES = new Set([
  "inc", "llc", "ltd", "plc", "corp", "corporation", "co", "company", "group",
  "llp", "gmbh", "sa", "nv", "holdings", "international", "worldwide",
]);

export const PLACE_NOISE = new Set([
  "greater", "area", "metro", "metropolitan", "county", "region", "the",
]);
